clean up

diff --git a/.github/workflows/benchmark-test.yml b/.github/workflows/benchmark-test.yml
--- a/.github/workflows/benchmark-test.yml
+++ b/.github/workflows/benchmark-test.yml
@@ -43,8 +43,8 @@ jobs:
           cd docker.local/benchmarks
           ../bin/start.benchmarks.sh | tee benchmark_run_output
           grep -R "Results" -A 1000 benchmark_run_output > benchmark_results
+          echo "TESTS_RAN=true" >> $GITHUB_ENV   
           if grep -aq "FAILED" benchmark_results; then
-            echo "TESTS_RAN=false" >> $GITHUB_ENV
-          else
-            echo "TESTS_RAN=true" >> $GITHUB_ENV
-          fi 
+            echo "::error::Benchmark tests failed"
+            exit 1
+          fi
