removed: system tests

diff --git a/.github/workflows/build-&-publish-docker-image.yml b/.github/workflows/build-&-publish-docker-image.yml
--- a/.github/workflows/build-&-publish-docker-image.yml
+++ b/.github/workflows/build-&-publish-docker-image.yml
@@ -201,95 +201,95 @@ jobs:
           docker push $SHARDER_REGISTRY:latest
 
 
-  system-tests:
-    if: ${{ github.event_name != 'workflow_dispatch' }}
-    needs: [miner, sharder]
-    runs-on: [ tests-suite ]
-    steps:
-      - name: "Get current PR"
-        uses: jwalton/gh-find-current-pr@v1
-        id: findPr
-        with:
-          github-token: ${{ github.token }}
+  # system-tests:
+  #   if: ${{ github.event_name != 'workflow_dispatch' }}
+  #   needs: [miner, sharder]
+  #   runs-on: [ tests-suite ]
+  #   steps:
+  #     - name: "Get current PR"
+  #       uses: jwalton/gh-find-current-pr@v1
+  #       id: findPr
+  #       with:
+  #         github-token: ${{ github.token }}
 
-      - name: "Set PR status as pending"
-        uses: 0chain/actions/set-pr-status@master
-        if: steps.findPr.outputs.number
-        with:
-          pr_number: ${{ steps.findPr.outputs.pr }}
-          description: "System tests running with default config..."
-          state: "pending"
-          repository: ${{ github.repository }}
-          status_name: "0Chain System Tests"
-          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-          github_token: ${{ github.token }}
+  #     - name: "Set PR status as pending"
+  #       uses: 0chain/actions/set-pr-status@master
+  #       if: steps.findPr.outputs.number
+  #       with:
+  #         pr_number: ${{ steps.findPr.outputs.pr }}
+  #         description: "System tests running with default config..."
+  #         state: "pending"
+  #         repository: ${{ github.repository }}
+  #         status_name: "0Chain System Tests"
+  #         target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         github_token: ${{ github.token }}
 
-      - name: "Setup"
-        run: |
-          if [[ "${{github.ref}}" == refs/pull/* ]]; then
-            tag=${GITHUB_REF/\/merge/}
-            echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
-          else
-            echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
-          fi
+  #     - name: "Setup"
+  #       run: |
+  #         if [[ "${{github.ref}}" == refs/pull/* ]]; then
+  #           tag=${GITHUB_REF/\/merge/}
+  #           echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
+  #         else
+  #           echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
+  #         fi
 
-          echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
-          echo "SHORT_SHA=$(([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}') | head -c 8)" >> $GITHUB_ENV
+  #         echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
+  #         echo "SHORT_SHA=$(([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}') | head -c 8)" >> $GITHUB_ENV
 
-          echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
-          echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
+  #         echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
+  #         echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
           
-          if [[ "${{github.base_ref}}" == "staging" ]]; then
-            echo "REPO_SNAPSHOTS_BRANCH=<CURRENT BRANCH WITH FALLBACK TO STAGING>" >> $GITHUB_ENV
-          else
-            echo "REPO_SNAPSHOTS_BRANCH=<CURRENT BRANCH WITH FALLBACK TO CURRENT_SPRINT>" >> $GITHUB_ENV
-          fi
+  #         if [[ "${{github.base_ref}}" == "staging" ]]; then
+  #           echo "REPO_SNAPSHOTS_BRANCH=<CURRENT BRANCH WITH FALLBACK TO STAGING>" >> $GITHUB_ENV
+  #         else
+  #           echo "REPO_SNAPSHOTS_BRANCH=<CURRENT BRANCH WITH FALLBACK TO CURRENT_SPRINT>" >> $GITHUB_ENV
+  #         fi
 
-      - name: Ensure jq is installed
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y jq
-            jq --version
+  #     - name: Ensure jq is installed
+  #       run: |
+  #           sudo apt-get update
+  #           sudo apt-get install -y jq
+  #           jq --version
         
-      - name: "Deploy 0Chain"
-        uses: 0chain/actions/deploy-0chain@master
-        with:
-          miner_image: ${{ env.TAG }}-${{ env.SHORT_SHA }}
-          sharder_image: ${{ env.TAG }}-${{ env.SHORT_SHA }}
-          repo_snapshots_branch: ${{ env.REPO_SNAPSHOTS_BRANCH }}
-          svc_account_secret: ${{ secrets.SVC_ACCOUNT_SECRET }}
-          kube_config: ${{ secrets[format('DEV{0}KC', env.RUNNER_NUMBER)] }}
-          teardown_condition: "TESTS_PASSED"
-          SUBGRAPH_API_URL: ${{ secrets.SUBGRAPH_API_URL }}
-          TENDERLY_VIRTUAL_TESTNET_RPC_ID: ""
-          graphnode_sc: ${{ secrets.GRAPHNODE_SC }}
-          graphnode_network: ${{ secrets.GRAPHNODE_NETWORK }}
-          graphnode_ethereum_node_url: ""
+  #     - name: "Deploy 0Chain"
+  #       uses: 0chain/actions/deploy-0chain@master
+  #       with:
+  #         miner_image: ${{ env.TAG }}-${{ env.SHORT_SHA }}
+  #         sharder_image: ${{ env.TAG }}-${{ env.SHORT_SHA }}
+  #         repo_snapshots_branch: ${{ env.REPO_SNAPSHOTS_BRANCH }}
+  #         svc_account_secret: ${{ secrets.SVC_ACCOUNT_SECRET }}
+  #         kube_config: ${{ secrets[format('DEV{0}KC', env.RUNNER_NUMBER)] }}
+  #         teardown_condition: "TESTS_PASSED"
+  #         SUBGRAPH_API_URL: ${{ secrets.SUBGRAPH_API_URL }}
+  #         TENDERLY_VIRTUAL_TESTNET_RPC_ID: ""
+  #         graphnode_sc: ${{ secrets.GRAPHNODE_SC }}
+  #         graphnode_network: ${{ secrets.GRAPHNODE_NETWORK }}
+  #         graphnode_ethereum_node_url: ""
 
-      - name: "Run System tests"
-        uses: 0chain/actions/run-system-tests@master
-        with:
-          repo_snapshots_branch: ${{ env.REPO_SNAPSHOTS_BRANCH }}
-          network: ${{ env.NETWORK_URL }}
-          svc_account_secret: ${{ secrets.SVC_ACCOUNT_SECRET }}
-          deploy_report_page: false
-          archive_results: true
-          run_flaky_tests: false
-          run_smoke_tests: ${{ github.ref != 'refs/heads/staging' && github.base_ref != 'staging' && github.ref != 'refs/heads/master' && github.base_ref != 'master' }}
-          retry_failures: true
-          TENDERLY_VIRTUAL_TESTNET_RPC_ID: ""
-          DEVOPS_CHANNEL_WEBHOOK_URL: ${{ secrets.DEVOPS_CHANNEL_WEBHOOK_URL }}
-          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
-          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
+  #     - name: "Run System tests"
+  #       uses: 0chain/actions/run-system-tests@master
+  #       with:
+  #         repo_snapshots_branch: ${{ env.REPO_SNAPSHOTS_BRANCH }}
+  #         network: ${{ env.NETWORK_URL }}
+  #         svc_account_secret: ${{ secrets.SVC_ACCOUNT_SECRET }}
+  #         deploy_report_page: false
+  #         archive_results: true
+  #         run_flaky_tests: false
+  #         run_smoke_tests: ${{ github.ref != 'refs/heads/staging' && github.base_ref != 'staging' && github.ref != 'refs/heads/master' && github.base_ref != 'master' }}
+  #         retry_failures: true
+  #         TENDERLY_VIRTUAL_TESTNET_RPC_ID: ""
+  #         DEVOPS_CHANNEL_WEBHOOK_URL: ${{ secrets.DEVOPS_CHANNEL_WEBHOOK_URL }}
+  #         S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
+  #         S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
 
-      - name: "Set PR status as ${{ job.status }}"
-        if: ${{ (success() || failure()) && steps.findPr.outputs.number }}
-        uses: 0chain/actions/set-pr-status@master
-        with:
-          pr_number: ${{ steps.findPr.outputs.pr }}
-          description: "System tests with default config"
-          state: ${{ job.status }}
-          repository: ${{ github.repository }}
-          status_name: "0Chain System Tests"
-          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-          github_token: ${{ github.token }}
+  #     - name: "Set PR status as ${{ job.status }}"
+  #       if: ${{ (success() || failure()) && steps.findPr.outputs.number }}
+  #       uses: 0chain/actions/set-pr-status@master
+  #       with:
+  #         pr_number: ${{ steps.findPr.outputs.pr }}
+  #         description: "System tests with default config"
+  #         state: ${{ job.status }}
+  #         repository: ${{ github.repository }}
+  #         status_name: "0Chain System Tests"
+  #         target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         github_token: ${{ github.token }}
