fixing notification on slack

diff --git a/.github/workflows/conductor-byzantine-tests.yml b/.github/workflows/conductor-byzantine-tests.yml
--- a/.github/workflows/conductor-byzantine-tests.yml
+++ b/.github/workflows/conductor-byzantine-tests.yml
@@ -24,37 +24,37 @@ jobs:
       branch: ${{ steps.chain.outputs.BRANCH_OUT }}
 
     steps:
-    - name: Cleanup before restarting conductor tests.
-      run: |
-        rm -rf *
+    # - name: Cleanup before restarting conductor tests.
+    #   run: |
+    #     rm -rf *
 
     # - uses: actions/checkout@v1
 
-    - name: "Setup Go"
-      shell: 'script --return --quiet --command "bash {0}"'
-      run: |
-        [ -f ./https://go.dev/dl/go1.20.3.linux-amd64.tar.gz ] || wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
-        [ -d /usr/local/go ] &&  rm -rf /usr/local/go
-        [ -f /usr/local/bin/go ] &&  rm -rf /usr/local/bin/go
-        tar -C /usr/local -xzf ./go1.20.3.linux-amd64.tar.gz
+    # - name: "Setup Go"
+    #   shell: 'script --return --quiet --command "bash {0}"'
+    #   run: |
+    #     [ -f ./https://go.dev/dl/go1.20.3.linux-amd64.tar.gz ] || wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
+    #     [ -d /usr/local/go ] &&  rm -rf /usr/local/go
+    #     [ -f /usr/local/bin/go ] &&  rm -rf /usr/local/bin/go
+    #     tar -C /usr/local -xzf ./go1.20.3.linux-amd64.tar.gz
 
-        echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
-        export PATH=$PATH:/usr/local/go/bin
-        export HOME="/root"
-        which go
-        go env
+    #     echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
+    #     export PATH=$PATH:/usr/local/go/bin
+    #     export HOME="/root"
+    #     which go
+    #     go env
 
-    - name: Docker Compose Setup.
-      run: |
-        sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
-        sudo chmod +x /usr/local/bin/docker-compose
-        docker-compose --version
+    # - name: Docker Compose Setup.
+    #   run: |
+    #     sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
+    #     sudo chmod +x /usr/local/bin/docker-compose
+    #     docker-compose --version
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    # - name: Login to Docker Hub
+    #   uses: docker/login-action@v2
+    #   with:
+    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
     # - name: Install herumi/bls and herumi/mcl
     #   run: |
@@ -66,9 +66,9 @@ jobs:
     - name: Git clone 0chain
       id: chain
       run: |
-        git clone https://github.com/0chain/0chain.git
+        # git clone https://github.com/0chain/0chain.git
         cd 0chain
-        git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done || true
+        # git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done || true
         CHAIN_BRANCH="${{ inputs.chain_branch }}"
         if [[ -z $CHAIN_BRANCH ]]; then
           echo "Checking for latest sprint branch"
