test notify

diff --git a/.github/workflows/conductor-tests.yml b/.github/workflows/conductor-tests.yml
--- a/.github/workflows/conductor-tests.yml
+++ b/.github/workflows/conductor-tests.yml
@@ -3,7 +3,7 @@ name: CONDUCTOR TESTS SUITE
 on:
   schedule:
     #   # Runs everyday at 02:00 am
-      - cron: '0 * * * *'
+      - cron: '* 0 * * *'
   workflow_dispatch:
     inputs:
       zchain-branch:
@@ -241,6 +241,122 @@ jobs:
     secrets:
       inherit
   
+  S1-1:
+    runs-on: self-hosted
+    steps:
+      - name: command
+        run: exit 0
+  S1-2:
+    runs-on: self-hosted
+    needs: S1-1
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+
+  S1-3:
+    runs-on: self-hosted
+    needs: S1-2
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+
+  S2-1:
+    runs-on: self-hosted
+    steps:
+      - name: command
+        run: exit -1
+  S2-2:
+    runs-on: self-hosted
+    needs: S2-1
+    if: failure()
+    steps:
+      - name: command
+        run: exit 0
+
+  S2-3:
+    runs-on: self-hosted
+    needs: S2-2
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+
+  S3-1:
+    runs-on: self-hosted
+    steps:
+      - name: command
+        run: exit -1
+  S3-2:
+    runs-on: self-hosted
+    needs: S3-1
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+
+  S3-3:
+    runs-on: self-hosted
+    needs: S3-2
+    if: failure()
+    steps:
+      - name: command
+        run: exit 0
+  
+  F-1:
+    runs-on: self-hosted
+    steps:
+      - name: command
+        run: exit -1
+  F-2:
+    runs-on: self-hosted
+    needs: F-1
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+
+  F-3:
+    runs-on: self-hosted
+    needs: F-2
+    if: failure()
+    steps:
+      - name: command
+        run: exit -1
+  
+  test-output:
+    runs-on: self-hosted
+    needs: [S1-1, S1-2, S1-3, S2-1, S2-2, S2-3, S3-1, S3-2, S3-3, F-1, F-2, F-3]
+    steps:
+      - name: echo output
+        run: |
+          PASSED_TEXT="PASSED ✅"
+          FAILED_TEXT="FAILED ⚠️"
+          PASSED_COLOR="#22bb33"
+          FAILED_COLOR="#ff0000"
+
+          S1_STATUS=$([ "${{ needs.S1-1.result }}" = "success" || "${{ needs.S1-2.result }}" = "success" || "${{ needs.S1-3.result }}" = "success" ] && echo $PASSED_TEST || echo $FAILED_TEST)
+          S1_ATTEMPTS=$([ "${{ needs.S1-1.result}}" = "success" ] && echo "1" || echo "3")
+          S1_ATTEMPTS=$([ "${{ needs.S1-2.result}}" = "success" ] && echo "2" || echo "3")
+
+          S2_STATUS=$([ "${{ needs.S2-1.result }}" = "success" || "${{ needs.S2-2.result }}" = "success" || "${{ needs.S2-3.result }}" = "success" ] && echo $PASSED_TEST || echo $FAILED_TEST)
+          S2_ATTEMPTS=$([ "${{ needs.S2-1.result}}" = "success" ] && echo "1" || echo "3")
+          S2_ATTEMPTS=$([ "${{ needs.S2-2.result}}" = "success" ] && echo "2" || echo "3")
+
+          S3_STATUS=$([ "${{ needs.S3-1.result }}" = "success" || "${{ needs.S3-2.result }}" = "success" || "${{ needs.S3-3.result }}" = "success" ] && echo $PASSED_TEST || echo $FAILED_TEST)
+          S3_ATTEMPTS=$([ "${{ needs.S3-1.result}}" = "success" ] && echo "1" || echo "3")
+          S3_ATTEMPTS=$([ "${{ needs.S3-2.result}}" = "success" ] && echo "2" || echo "3")
+
+          F_STATUS=$([ "${{ needs.F-1.result }}" = "success" || "${{ needs.F-2.result }}" = "success" || "${{ needs.F-3.result }}" = "success" ] && echo $PASSED_TEST || echo $FAILED_TEST)
+          F_ATTEMPTS=$([ "${{ needs.F-1.result}}" = "success" ] && echo "1" || echo "3")
+          F_ATTEMPTS=$([ "${{ needs.F-2.result}}" = "success" ] && echo "2" || echo "3")
+      
+          echo "S1 = $S1_STATUS ($S1_ATTEMPTS/3)"
+          echo "S2 = $S2_STATUS ($S2_ATTEMPTS/3)"
+          echo "S3 = $S3_STATUS ($S3_ATTEMPTS/3)"
+          echo "S1 = $F_STATUS ($F_ATTEMPTS/3)"
+
   notify_slack:
     runs-on: [self-hosted, arc-runner]
     needs: [standard-miner, standard-sharder, zchain-config, byzantine-try-1, byzantine-try-2, byzantine-try-3, fault-tolerance, blobber-01, blobber-02-try-1, blobber-02-try-2, blobber-02-try-3, blobber-03, blobber-04, blobber-05, blobber-06, authorizers-standard, node-recovery-01, node-recovery-02-try-1, node-recovery-02-try-2, node-recovery-02-try-3, node-recovery-03]
@@ -269,8 +385,7 @@ jobs:
           ZCHAIN_CONFIG_STATUS=$([ "${{ needs.zchain-config.result }}" = "success" ] && echo "$PASSED_TEXT" || echo "$FAILED_TEXT")
           ZCHAIN_CONFIG_COLOR=$([ "${{ needs.zchain-config.result }}" = "success" ] && echo "$PASSED_COLOR" || echo "$FAILED_COLOR")
         
-          # FLAKY
-          BYZANTINE_STATUS=$([ "${{ needs.byzantine-try-1.result }}" = "success" || "${{ needs.byzantine-try-2.result }}" = "success" || "${{ needs.byzantine-try-2.result }}" = "success" ] && echo "$PASSED_TEXT" || echo "$FAILED_TEXT")
+          BYZANTINE_STATUS=$([ "${{ needs.byzantine-try-1.result }}" = "success" || "${{ needs.byzantine-try-2.result }}" = "success" || "${{ needs.byzantine-try-3.result }}" = "success" ] && echo "$PASSED_TEXT" || echo "$FAILED_TEXT")
           BYZANTINE_COLOR=$([ "$BYZANTINE_STATUS" = "$PASSED_TEXT " ] && echo "$PASSED_COLOR" || echo "$FAILED_COLOR")
           BYZANTINE_ATTEMPTS_COUNT=$([ "${{ needs.byzantine-try-1.result }}" = "success" ] && echo "1" || echo "3")
           BYZANTINE_ATTEMPTS_COUNT=$([ "${{ needs.byzantine-try-2.result }}" = "success" ] && echo "2" || echo "3")
@@ -281,7 +396,6 @@ jobs:
           BLOBBER_01_STATUS=$([ "${{ needs.blobber-01.result }}" = "success" ] && echo "$PASSED_TEXT" || echo "$FAILED_TEXT")
           BLOBBER_01_COLOR=$([ "${{ needs.blobber-01.result }}" = "success" ] && echo "$PASSED_COLOR" || echo "$FAILED_COLOR")
           
-          # FLAKY
           BLOBBER_02_STATUS=$([ "${{ needs.blobber-02-try-1.result }}" = "success" || "${{ needs.blobber-02-try-2.result }}" = "success" || "${{ needs.blobber-02-try-3.result }}" = "success" ] && echo "$PASSED_TEXT" || echo "$FAILED_TEXT")
           BLOBBER_02_COLOR=$([ "$BLOBBER_02_STATUS" = "$PASSED_TEXT" ] && echo "$PASSED_COLOR" || echo "$FAILED_COLOR")
           BLOBBER_02_ATTEMPTS_COUNT=$([ "${{ needs.blobber-02-try-1.result }}" = "success" ] && echo "1" || echo "3")
