delete duplicate flakiness wf file

diff --git a/.github/workflows/conductor-tests-flakiness.yaml b/.github/workflows/conductor-tests-flakiness.yaml
--- a/.github/workflows/conductor-tests-flakiness.yaml
+++ b/.github/workflows/conductor-tests-flakiness.yaml
@@ -41,15 +41,11 @@ env:
   ZDNS_URL: http://198.18.0.98:9091
 
 jobs:
-  CONDUCTOR_NODE_RECOVERY_03_TESTS:
+  CONDUCTOR_TESTS_FLAKINESS:
     name: CONDUCTOR-NODE-RECOVERY-03-TESTS
     runs-on: [self-hosted, conductor-test]
 
     steps:
-    - name: Install NodeJS
-      uses: actions/setup-node@v4
-      with:
-        node-version: '18'
 
     - name: Setup Environment Variables
       run: |
@@ -433,15 +429,46 @@ jobs:
       run: |
         cat ~/.zcn/wallets/UTC--2023-10-26T00-34-42.327566000Z--8e25cfd9bd6c0ca67a5522cd920b3c66d39d6e97
   
+    - name: Make logs directory
+      run: |
+        mkdir -p ./0chain/conductor-flakiness-logs
+    
+    - name: Initialize stats vars
+      run: |
+        echo CURRENT_ATTEMPT=0 >> "$GITHUB_ENV"
+        echo SUCCESSFUL_ATTEMPTS=0 >> "$GITHUB_ENV"
+        echo FAILED_ATTEMPTS=0 >> "$GITHUB_ENV"
+       
     - name: Start Flakiness Test
       uses: nick-fields/retry@v2
       with:
         max_attempts: ${{ inputs.number_of_times }}
         continue_on_error: ${{ inputs.continue_on_error }}
+        timeout_minutes: 120
         command: |
+          echo CURRENT_ATTEMPT=$(($CURRENT_ATTEMPT + 1)) >> $GITHUB_ENV
           export HOME="/root"
           cd 0chain
-          ./docker.local/bin/start.conductor.sh ${{ inputs.test_name }}
+          
+          ./docker.local/bin/start.conductor.sh
+          if [ $? -eq 0 ]; then
+            echo "[CT-FLAKY-LOG] Conductor test attempt $CURRENT_ATTEMPT succeeded ✅"
+            zip -r "condcutor-flakiness-logs-$CURRENT_ATTEMPT.zip" condcutor-flakiness-logs
+            echo SUCCESSFUL_ATTEMPTS=$(($SUCCESSFUL_ATTEMPTS + 1)) >> $GITHUB_ENV
+            exit 0
+          else
+            echo "[CT-FLAKY-LOG] Conductor test attempt $CURRENT_ATTEMPT failed ❌"
+            zip -r "condcutor-flakiness-logs-$CURRENT_ATTEMPT.zip" condcutor-flakiness-logs
+            echo FAILED_ATTEMPTS=$(($FAILED_ATTEMPTS + 1)) >> $GITHUB_ENV
+            exit 1
+          fi
+           
+
+    - name: "Log Stats"
+      run: |
+        echo "TOTAL_ATTEMPTS = $CURRENT_ATTEMPTS"
+        echo "SUCCESSFUL_ATTEMPTS = $SUCCESSFUL_ATTEMPTS"
+        echo "FAILED_ATTEMPTS = $FAILED_ATTEMPTS"
 
     - name: "Remove Tenderly fork"
       if: always()
@@ -454,11 +481,14 @@ jobs:
     - uses: actions/upload-artifact@v3
       if: always()
       with:
-        name: node-recovery-03-logs
+        name: conductor-flakiness-logs
         path: |
-          0chain/conductor-full-logs
+          0chain/conductor-flakiness-logs
 
-    - name: Added /tmp folder cleanup.
+    - name: Cleanup.
+      if: always()
       run: |
+        [ "$(docker ps -a -q)" ] && docker rm -f $(docker ps -a -q) || true
+        rm -rf ./0chain/conductor-full-logs
         cd /tmp
         rm -rf ./*
