Add custom network option

diff --git a/.github/workflows/manual-api-regressions.yml b/.github/workflows/manual-api-regressions.yml
--- a/.github/workflows/manual-api-regressions.yml
+++ b/.github/workflows/manual-api-regressions.yml
@@ -4,11 +4,16 @@ on:
   workflow_dispatch:
     inputs:
       network:
-        description: 'Which network do you want to run API regressions against? Valid options: beta | dev | grpc | magma | stream | test'
-        required: true
+        description: '[Overridden by custom network below] Which network do you want to run API regressions against? Valid options: beta | dev | grpc | magma | stream | test'
+        required: false
         default: 'beta'
+      custom_network:
+        description: '[OPTIONAL] Input custom network you wish to run tests against. eg. my_custom_network.0chain.net'
+        required: false
+        default: ''  
 
 env:
+  NETWORK: ${{ github.event.inputs.network }}
   NETWORKS: beta | dev | grpc | magma | stream | test
 
 jobs: 
@@ -17,7 +22,7 @@ jobs:
     steps:   
       - name: Validate network option
         id: network-check
-        run: (echo '${{ env.NETWORKS }}' | grep -w "${{ github.event.inputs.network }}" > /dev/null && echo '::set-output name=VALID_NETWORK::true') || (echo '::set-output name=VALID_NETWORK::false' && echo "INVALID NETWORK [${{ github.event.inputs.network }}] SUPPLIED" && exit 1)
+        run: (echo -n "${{ github.event.inputs.custom_network }}" | xargs | wc -c | grep -vw 1 && echo 'NETWORK=custom' >> $GITHUB_ENV) || (echo '${{ env.NETWORKS }}' | grep -w "${{ env.NETWORK }}" > /dev/null || (echo "INVALID NETWORK [${{ env.NETWORK }}] SUPPLIED" && exit 1))
    
       - name: checkout
         uses: actions/checkout@v2
@@ -36,7 +41,7 @@ jobs:
          npm install -g newman-reporter-htmlextra
 
       - name: Make Directory for results
-        run: mkdir -p ./${BRANCH}/latest
+        run: mkdir -p ./${{ env.NETWORK }}/latest
         
       - name: Get Time
         id: time
@@ -46,17 +51,18 @@ jobs:
 
       - name: Run POSTMAN collection
         run: |
-           exit_code=0
-           newman run "./Postman Collections/0chain-regressions.json" -e "./Postman Collections/Environments/${{ github.event.inputs.network }}.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export "./${{ github.event.inputs.network }}/latest/index.html" --reporter-htmlextra-darkTheme --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-showGlobalData --reporter-htmlextra-logs --reporter-htmlextra-title "0Chain API Regression Tests" --reporter-htmlextra-template "./Postman Collections/Data/0chain-dashboard-template.hbs" --reporter-htmlextra-browserTitle "tested against ${{ github.event.inputs.network }} network"  --color on || exit_code=$? 
-           cp -R ./${{ github.event.inputs.network }}/latest ./${{ github.event.inputs.network }}/${{ steps.time.outputs.time }}
+           exit_code=0           
+           (echo ${{ env.NETWORK }} | grep -w "custom" > /dev/null && custom_network=$(echo ${{ github.event.inputs.custom_network }} | xargs | sed -E 's/^\s*.*:\/\///g') && sed -i "0,/REPLACE/s//$custom_network/" './Postman Collections/Environments/custom.postman_environment.json') || custom_network=""
+           newman run "./Postman Collections/0chain-regressions.json" -e "./Postman Collections/Environments/${{ env.NETWORK }}.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export "./${{ env.NETWORK }}/latest/index.html" --reporter-htmlextra-darkTheme --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-showGlobalData --reporter-htmlextra-logs --reporter-htmlextra-title "0Chain API Regression Tests" --reporter-htmlextra-template "./Postman Collections/Data/0chain-dashboard-template.hbs" --reporter-htmlextra-browserTitle "tested against ${{ env.NETWORK }} network ${{ github.event.inputs.custom_network }}"  --color on || exit_code=$? 
+           cp -R ./${{ env.NETWORK }}/latest ./${{ env.NETWORK }}/${{ steps.time.outputs.time }}
            exit $exit_code
     
       - name: Output the run Details
         if: always()
         uses: actions/upload-artifact@v2
         with: 
-         name: "TestReport-${{ github.event.inputs.network }}-${{ steps.time.outputs.time }}"
-         path: "./${{ github.event.inputs.network }}/latest"
+         name: "TestReport-${{ env.NETWORK }}-${{ steps.time.outputs.time }}"
+         path: "./${{ env.NETWORK }}/latest"
          
       - name: Deploy report page
         if:  always()
@@ -65,11 +71,11 @@ jobs:
           publish_branch: test_reports
           keep_files: true
           github_token: "${{ secrets.SVC_ACCOUNT_SECRET }}"
-          publish_dir: "./${{ github.event.inputs.network }}"
-          destination_dir: "./${{ github.event.inputs.network }}"
+          publish_dir: "./${{ env.NETWORK }}"
+          destination_dir: "./${{ env.NETWORK }}"
           user_name: "github-actions[bot]"
           user_email: "github-actions[bot]@users.noreply.github.com"    
           
       - name: Report Link
         if:  always()
-        run: echo "https://0chain.github.io/0chain/${{ github.event.inputs.network }}/${{ steps.time.outputs.time }}" 
+        run: echo "https://0chain.github.io/0chain/${{ env.NETWORK }}/${{ steps.time.outputs.time }}" 
