allow manual tests to run from branch

diff --git a/.github/workflows/system_tests.yml b/.github/workflows/system_tests.yml
--- a/.github/workflows/system_tests.yml
+++ b/.github/workflows/system_tests.yml
@@ -19,19 +19,19 @@ on:
         description: '0Wallet CLI (branch or commit SHA) which the tests will use'
         default: 'staging'
         required: true
-       blobber_image:
-        description: 'blobber DOCKER IMAGE to deploy'
+       blobber_branch:
+        description: 'blobber branch to deploy'
         default: 'staging'
         required: true
-       validator_image:
+       validator_branch:
         description: 'validator DOCKER IMAGE to deploy'
         default: 'staging'
         required: true
-       zbox_image:
+       zbox_branch:
         description: '0box DOCKER IMAGE to deploy'
         default: 'staging'
         required: true
-       zblock_image:
+       zblock_branch:
         description: '0block DOCKER IMAGE to deploy'
         default: 'staging'
         required: true
@@ -48,61 +48,46 @@ jobs:
 
     - name: "Setup Test Run"
       run: |
-        echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV
-        echo "TAG=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g')" >> $GITHUB_ENV
         echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
         echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
 
-    - name: "Check miner image has been published"
-      if: ${{ github.event.inputs.skip_tests == 'FALSE' }}
-      run: |
+        echo '#!/bin/bash
         exit_code=0
-        echo "Checking miner image [${{ env.TAG }}-${{ env.SHORT_SHA }}] is present..."
-        docker pull 0chaindev/miner:${{ env.TAG }}-${{ env.SHORT_SHA }} || exit_code=$?
+        SHORT_SHA=$(curl --silent https://api.github.com/repos/0chain/$1/git/refs/heads/$2 | jq --raw-output .object.sha | head -c 8)
+        PR_ID=$(curl --silent https://api.github.com/search/issues?q=sha:$SHORT_SHA | jq --raw-output .items[0].number)
+        TAG=$(echo $2 | sed '"'"'s/\//-/g'"'"')
+
+        echo "Checking [$3] image [${TAG}-${SHORT_SHA}] is present..."
+        docker pull 0chaindev/$3:${TAG}-${SHORT_SHA} || exit_code=$?
 
         if [[ $exit_code == 0 ]];
           then
-            echo "miner docker image found for  [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
-            echo "MINER_IMAGE=${{ env.TAG }}-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
+            echo "docker image found for  [${TAG}-${SHORT_SHA}]"
+            echo "IMAGE_$(echo $3 | awk '"'"'{ print toupper($0) }'"'"')=${TAG}-${SHORT_SHA}" >> $GITHUB_ENV
           else
-            if [ -z "${{ steps.findPr.outputs.pr }}" ];
+            if [ -z "$PR_ID" ];
               then
-                echo "miner docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}] and PR not raised so will not check for PR merge image. Please publish image manually. at https://github.com/0chain/0chain/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1;
+                echo "docker image NOT found for [${TAG}-${SHORT_SHA}] and PR not raised so will not check for PR merge image. Please publish image manually. at https://github.com/0chain/0chain/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1;
             fi
-            echo "miner docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
-            git fetch origin pull/${{ steps.findPr.outputs.pr }}/merge:merge && git checkout merge
-            MERGE_SHORT_SHA=$(git rev-parse HEAD | head -c 8)
-            echo "Checking miner image [merge-$MERGE_SHORT_SHA] is present..."
-            docker pull 0chaindev/miner:merge-$MERGE_SHORT_SHA || { echo "Docker image for miner could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge commit sha [$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/0chain/actions/workflows/build-&-publish-docker-image.yml and try again." && exit 1; }
-            echo "miner docker image found for [merge-$MERGE_SHORT_SHA]"
-            echo "MINER_IMAGE=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "miner docker image NOT found for [${TAG}-${SHORT_SHA}]"
+            MERGE_SHORT_SHA=$(curl --silent https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
+            echo "Checking image [merge-$MERGE_SHORT_SHA] is present..."
+            docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA || { echo "Docker image could not be found for either branch commit sha [${SHORT_SHA}] or PR merge commit sha [$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again." && exit 1; }
+            echo "docker image found for [merge-$MERGE_SHORT_SHA]"
+            echo "IMAGE_$(echo $3 | awk '"'"'{ print toupper($0) }'"'"')=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
+        ' > ./get_tag.sh;
+        chmod 777 ./get_tag.sh;
 
-    - name: "Check sharder image has been published"
+    - name: "Check images have been published"
       if: ${{ github.event.inputs.skip_tests == 'FALSE' }}
       run: |
-        exit_code=0
-        echo "Checking sharder image [${{ env.TAG }}-${{ env.SHORT_SHA }}] is present..."
-        docker pull 0chaindev/sharder:${{ env.TAG }}-${{ env.SHORT_SHA }} || exit_code=$?
-
-        if [[ $exit_code == 0 ]];
-          then
-            echo "sharder docker image found for  [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
-            echo "SHARDER_IMAGE=${{ env.TAG }}-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
-          else
-            if [ -z "${{ steps.findPr.outputs.pr }}" ];
-              then
-                echo "sharder docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}] and PR not raised so will not check for PR merge image. Please publish image manually." && exit 1;
-            fi
-            echo "sharder docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
-            git fetch origin pull/${{ steps.findPr.outputs.pr }}/merge:merge && git checkout merge
-            MERGE_SHORT_SHA=$(git rev-parse HEAD | head -c 8)
-            echo "Checking sharder image [merge-$MERGE_SHORT_SHA] is present..."
-            docker pull 0chaindev/sharder:merge-$MERGE_SHORT_SHA || { echo "Docker image for sharder could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge sha [$MERGE_SHORT_SHA]. Please publish image manually and try again." && exit 1; }
-            echo "sharder docker image found for [merge-$MERGE_SHORT_SHA]"
-            echo "SHARDER_IMAGE=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
-        fi
-
+        ./get_tag.sh 0chain ${GITHUB_REF##*/} miner
+        ./get_tag.sh 0chain ${GITHUB_REF##*/} sharder
+        ./get_tag.sh blobber ${{ github.event.inputs.blobber_branch }} blobber
+        ./get_tag.sh blobber ${{ github.event.inputs.validator_branch }} validator
+        ./get_tag.sh 0box ${{ github.event.inputs.zbox_branch }} 0box
+        ./get_tag.sh 0block ${{ github.event.inputs.zblock_branch }} 0block
 
     - name: "Set PR Status Pending"
       uses: 0chain/actions/notify-pull-request@feature/notify-PR-convenience
