fix(devops): improved docker push (#823)
* fix(devops): improved docker push

* fix(devops): fixed invalid syntax

* fix(devops): fixed invalid syntax

* fix(devops): fixed GITHUB_ENV

* fix(devops): fixed depends-on

* fix(devops): fixed docker image tag bug for pr

* fix(devops): fixed docker image tag bug for pr

* fix(devops): fixed docker image tag bug for pr

diff --git a/.github/workflows/system_tests.yml b/.github/workflows/system_tests.yml
--- a/.github/workflows/system_tests.yml
+++ b/.github/workflows/system_tests.yml
@@ -55,7 +55,7 @@ jobs:
     - name: "Setup Test Run"
       run: |
         echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV
-        echo "TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
+        echo "TAG=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g')" >> $GITHUB_ENV
         echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
         echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV
 
@@ -78,10 +78,10 @@ jobs:
             echo "miner docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
             git fetch origin pull/${{ steps.findPr.outputs.pr }}/merge:merge && git checkout merge
             MERGE_SHORT_SHA=$(git rev-parse HEAD | head -c 8)
-            echo "Checking miner image [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA] is present..."
-            docker pull 0chaindev/miner:refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA || { echo "Docker image for miner could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge commit sha [$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/0chain/actions/workflows/build-&-publish-docker-image.yml and try again." && exit 1; }
-            echo "miner docker image found for  [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA]"
-            echo "MINER_IMAGE=refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "Checking miner image [merge-$MERGE_SHORT_SHA] is present..."
+            docker pull 0chaindev/miner:merge-$MERGE_SHORT_SHA || { echo "Docker image for miner could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge commit sha [$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/0chain/actions/workflows/build-&-publish-docker-image.yml and try again." && exit 1; }
+            echo "miner docker image found for [merge-$MERGE_SHORT_SHA]"
+            echo "MINER_IMAGE=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
 
     - name: "Check sharder image has been published"
@@ -103,10 +103,10 @@ jobs:
             echo "sharder docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
             git fetch origin pull/${{ steps.findPr.outputs.pr }}/merge:merge && git checkout merge
             MERGE_SHORT_SHA=$(git rev-parse HEAD | head -c 8)
-            echo "Checking sharder image [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA] is present..."
-            docker pull 0chaindev/sharder:refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA || { echo "Docker image for sharder could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge sha [$MERGE_SHORT_SHA]. Please publish image manually and try again." && exit 1; }
-            echo "sharder docker image found for  [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA]"
-            echo "SHARDER_IMAGE=refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "Checking sharder image [merge-$MERGE_SHORT_SHA] is present..."
+            docker pull 0chaindev/sharder:merge-$MERGE_SHORT_SHA || { echo "Docker image for sharder could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge sha [$MERGE_SHORT_SHA]. Please publish image manually and try again." && exit 1; }
+            echo "sharder docker image found for [merge-$MERGE_SHORT_SHA]"
+            echo "SHARDER_IMAGE=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
 
 
