fix naming convention in manual system tests for 0chain repo

diff --git a/.github/workflows/system_tests.yml b/.github/workflows/system_tests.yml
--- a/.github/workflows/system_tests.yml
+++ b/.github/workflows/system_tests.yml
@@ -104,10 +104,10 @@ jobs:
             echo "sharder docker image NOT found for [${{ env.TAG }}-${{ env.SHORT_SHA }}]"
             git fetch origin pull/${{ steps.findPr.outputs.pr }}/merge:merge && git checkout merge
             MERGE_SHORT_SHA=$(git rev-parse HEAD | head -c 8)
-            echo "Checking sharder image [merge-$MERGE_SHORT_SHA] is present..."
-            docker pull 0chaindev/sharder:merge-$MERGE_SHORT_SHA || { echo "Docker image for sharder could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge sha [$MERGE_SHORT_SHA]. Please publish image manually and try again." && exit 1; }
-            echo "sharder docker image found for  [merge-$MERGE_SHORT_SHA]"
-            echo "SHARDER_IMAGE=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
+            echo "Checking sharder image [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA] is present..."
+            docker pull 0chaindev/sharder:refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA || { echo "Docker image for sharder could not be found for either branch commit sha [${{ env.SHORT_SHA }}] or PR merge sha [$MERGE_SHORT_SHA]. Please publish image manually and try again." && exit 1; }
+            echo "sharder docker image found for  [refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA]"
+            echo "SHARDER_IMAGE=refs-pull-${{ steps.findPr.outputs.pr }}-merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
 
 
