improve logging

diff --git a/.github/workflows/system_tests.yml b/.github/workflows/system_tests.yml
--- a/.github/workflows/system_tests.yml
+++ b/.github/workflows/system_tests.yml
@@ -72,12 +72,12 @@ jobs:
           else
             if [ -z "$PR_ID" ];
               then
-                echo "::error title=$3 docker image not found::Docker image NOT found for [${TAG}-${SHORT_SHA}] and PR not raised so will not check for PR merge image. Please publish image manually. at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
+                echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [${TAG}-${SHORT_SHA}]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1
             fi
             echo "Docker image NOT found for [${TAG}-${SHORT_SHA}]"
             MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)
             echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
-            docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null || { echo "::error title=$3 docker image not found::Docker image could not be found for either branch commit sha [${SHORT_SHA}] or PR merge commit sha [$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1; }
+            docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null || { echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again" && exit 1; }
             echo "Docker image found for [merge-$MERGE_SHORT_SHA]"
             echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
         fi
